import { publicAsset } from "../utils/publicAsset";
export interface BirthdayPhoto {
  id: number;
  src: string;
  fallbackSrcs?: string[];
  originalFilename: string;
  alt: string;
  category: "hero" | "birthday" | "travel" | "closing";
  caption?: string;
  subCaption?: string;
  focalPoint?: string;
  orientation?: "portrait" | "landscape";
}

export const galleryPhotos: BirthdayPhoto[] = [
  // 1. Portada Protagonista (Foto 9)
  {
    id: 9,
    src: publicAsset("/media/photos/hero-vale.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/foto-09.webp"),
      publicAsset("/media/photos/Foto 9.jpeg"),
      publicAsset("/media/photos/photo-09.jpg"),
      publicAsset("/media/photos/hero-vale.jpg"),
    ],
    originalFilename: "Foto 9.jpeg",
    alt: "Vale sonriendo en su día especial",
    category: "hero",
    caption: "Qué felicidad que existas",
    subCaption: "Fotografía 09 · Portada",
    focalPoint: "center",
    orientation: "portrait",
  },

  // 2. Carrusel de Cumpleaños (8 Dedicatorias: Fotos 6, 3, 5, 14, 1, 19, 24, 12)
  {
    id: 6,
    src: publicAsset("/media/photos/foto-06.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/Foto 6.jpeg"),
      publicAsset("/media/photos/photo-06.jpg"),
    ],
    originalFilename: "Foto 6.jpeg",
    alt: "La sonrisa luminosa de Vale",
    category: "birthday",
    caption: "Que nunca te falte esa sonrisa",
    subCaption: "Fotografía 06 · Razón 01",
    orientation: "portrait",
  },
  {
    id: 3,
    src: publicAsset("/media/photos/foto-03.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/Foto 3.jpeg"),
      publicAsset("/media/photos/photo-03.jpg"),
    ],
    originalFilename: "Foto 3.jpeg",
    alt: "Momentos de sorpresa y alegría de Vale",
    category: "birthday",
    caption: "Que la vida nunca deje de sorprenderte",
    subCaption: "Fotografía 03 · Razón 02",
    orientation: "landscape",
  },
  {
    id: 5,
    src: publicAsset("/media/photos/foto-05.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/Foto 5.jpeg"),
      publicAsset("/media/photos/photo-05.jpg"),
    ],
    originalFilename: "Foto 5.jpeg",
    alt: "Aventuras y planes espontáneos",
    category: "birthday",
    caption: "Que sigan llegando aventuras",
    subCaption: "Fotografía 05 · Razón 03",
    orientation: "portrait",
  },
  {
    id: 14,
    src: publicAsset("/media/photos/foto-14.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/Foto 14.jpeg"),
      publicAsset("/media/photos/photo-14.jpg"),
    ],
    originalFilename: "Foto 14.jpeg",
    alt: "Brindando por los sueños y logros de Vale",
    category: "birthday",
    caption: "Brindo por todo lo bonito que viene",
    subCaption: "Fotografía 14 · Razón 04",
    orientation: "portrait",
  },
  {
    id: 1,
    src: publicAsset("/media/photos/foto-01.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/Foto 1.jpeg"),
      publicAsset("/media/photos/photo-01.jpg"),
    ],
    originalFilename: "Foto 1.jpeg",
    alt: "La autenticidad y ternura de Vale",
    category: "birthday",
    caption: "Por tu ternura y tus locuras",
    subCaption: "Fotografía 01 · Razón 05",
    orientation: "portrait",
  },
  {
    id: 19,
    src: publicAsset("/media/photos/foto-19.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/Foto 19.jpeg"),
      publicAsset("/media/photos/photo-19.jpg"),
    ],
    originalFilename: "Foto 19.jpeg",
    alt: "Vale disfrutando de las cosas sencillas",
    category: "birthday",
    caption: "Que nunca te falten ganas de disfrutar",
    subCaption: "Fotografía 19 · Razón 06",
    orientation: "portrait",
  },
  {
    id: 24,
    src: publicAsset("/media/photos/foto-24.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/Foto 24.jpeg"),
      publicAsset("/media/photos/photo-24.jpg"),
    ],
    originalFilename: "Foto 24.jpeg",
    alt: "Todas las versiones admirables de Vale",
    category: "birthday",
    caption: "Por todas las versiones de ti",
    subCaption: "Fotografía 24 · Razón 07",
    orientation: "portrait",
  },
  {
    id: 12,
    src: publicAsset("/media/photos/foto-12.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/Foto 12.jpeg"),
      publicAsset("/media/photos/photo-12.jpg"),
    ],
    originalFilename: "Foto 12.jpeg",
    alt: "Pidiendo deseos en su cumpleaños",
    category: "birthday",
    caption: "Hoy pide todos los deseos que quieras",
    subCaption: "Fotografía 12 · Razón 08",
    orientation: "portrait",
  },

  // 3. Sección de Viajes y Aventuras (Fotos 2, 4, 7, 8, 11, 13, 15, 16, 17, 18, 20, 21, 22, 23)
  {
    id: 2,
    src: publicAsset("/media/photos/foto-02.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/foto 2.jpeg"),
      publicAsset("/media/photos/Foto 2.jpeg"),
      publicAsset("/media/photos/photo-02.jpg"),
    ],
    originalFilename: "foto 2.jpeg",
    alt: "Vale en paisaje nevado",
    category: "travel",
    caption: "y que siempre esos lugares estén llenos de tu alegría, tu sonrisa hermosa y ese amor que te hace brillar",
    subCaption: "Fotografía 02 · Nieve",
    orientation: "landscape",
  },
  {
    id: 4,
    src: publicAsset("/media/photos/foto-04.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/foto 4.jpeg"),
      publicAsset("/media/photos/Foto 4.jpeg"),
      publicAsset("/media/photos/photo-04.jpg"),
    ],
    originalFilename: "foto 4.jpeg",
    alt: "Montaña y paisaje de nieve",
    category: "travel",
    caption: "lugares únicos",
    subCaption: "Fotografía 04 · Altura",
    orientation: "portrait",
  },
  {
    id: 7,
    src: publicAsset("/media/photos/foto-07.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/foto 7.jpeg"),
      publicAsset("/media/photos/Foto 7.jpeg"),
      publicAsset("/media/photos/photo-07.jpg"),
    ],
    originalFilename: "foto 7.jpeg",
    alt: "Aventuras al aire libre",
    category: "travel",
    caption: "viajes bonitos en familia",
    subCaption: "Fotografía 07 · Ruta",
    orientation: "portrait",
  },
  {
    id: 8,
    src: publicAsset("/media/photos/foto-08.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/Foto 8 .jpeg"),
      publicAsset("/media/photos/Foto 8.jpeg"),
      publicAsset("/media/photos/photo-08.jpg"),
    ],
    originalFilename: "Foto 8 .jpeg",
    alt: "Paisaje montañoso espectacular",
    category: "travel",
    caption: "Vistas que quitan el aliento",
    subCaption: "Fotografía 08 · Montaña",
    orientation: "landscape",
  },
  {
    id: 11,
    src: publicAsset("/media/photos/foto-11.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/Foto 11.jpeg"),
      publicAsset("/media/photos/photo-11.jpg"),
    ],
    originalFilename: "Foto 11.jpeg",
    alt: "Embarcación y mar abierto",
    category: "travel",
    caption: "Navegando hacia nuevos horizontes",
    subCaption: "Fotografía 11 · Mar",
    orientation: "landscape",
  },
  {
    id: 13,
    src: publicAsset("/media/photos/foto-13.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/Foto 13.jpeg"),
      publicAsset("/media/photos/photo-13.jpg"),
    ],
    originalFilename: "Foto 13.jpeg",
    alt: "Paisaje urbano descubierto juntos",
    category: "travel",
    caption: "Calles nuevas y esquinas mágicas",
    subCaption: "Fotografía 13 · Ciudad",
    orientation: "portrait",
  },
  {
    id: 15,
    src: publicAsset("/media/photos/foto-15.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/foto 15.jpeg"),
      publicAsset("/media/photos/Foto 15.jpeg"),
      publicAsset("/media/photos/photo-15.jpg"),
    ],
    originalFilename: "foto 15.jpeg",
    alt: "Detalles del viaje",
    category: "travel",
    caption: "lugares en los que seas tú",
    subCaption: "Fotografía 15 · Detalle",
    orientation: "portrait",
  },
  {
    id: 16,
    src: publicAsset("/media/photos/foto-16.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/foto 16.jpeg"),
      publicAsset("/media/photos/Foto 16.jpeg"),
      publicAsset("/media/photos/photo-16.jpg"),
    ],
    originalFilename: "foto 16.jpeg",
    alt: "Explorando rincones",
    category: "travel",
    caption: "Descubriendo el mundo paso a paso",
    subCaption: "Fotografía 16 · Rincones",
    orientation: "landscape",
  },
  {
    id: 17,
    src: publicAsset("/media/photos/foto-17.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/Foto 17.jpeg"),
      publicAsset("/media/photos/photo-17.jpg"),
    ],
    originalFilename: "Foto 17.jpeg",
    alt: "Mirador y señalización turística",
    category: "travel",
    caption: "Puntos cardinales y nuevos destinos",
    subCaption: "Fotografía 17 · Mirador",
    orientation: "portrait",
  },
  {
    id: 18,
    src: publicAsset("/media/photos/foto-18.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/Foto 18.jpeg"),
      publicAsset("/media/photos/photo-18.jpg"),
    ],
    originalFilename: "Foto 18.jpeg",
    alt: "Paisaje urbano junto al agua",
    category: "travel",
    caption: "días de planes únicos, de planes que sean como tú",
    subCaption: "Fotografía 18 · Ribera",
    orientation: "landscape",
  },
  {
    id: 20,
    src: publicAsset("/media/photos/foto-20.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/Foto 20.jpeg"),
      publicAsset("/media/photos/photo-20.jpg"),
    ],
    originalFilename: "Foto 20.jpeg",
    alt: "Ambiente urbano nocturno",
    category: "travel",
    caption: "caminar por el mundo... amándote por el mundo",
    subCaption: "Fotografía 20 · Noche",
    orientation: "portrait",
  },
  {
    id: 21,
    src: publicAsset("/media/photos/foto-21.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/Foto 21.jpeg"),
      publicAsset("/media/photos/photo-21.jpg"),
    ],
    originalFilename: "Foto 21.jpeg",
    alt: "Paisaje nocturno iluminado",
    category: "travel",
    caption: "la magia que le das al mundo",
    subCaption: "Fotografía 21 · Postal",
    orientation: "landscape",
  },
  {
    id: 22,
    src: publicAsset("/media/photos/foto-22.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/Foto 22.jpeg"),
      publicAsset("/media/photos/photo-22.jpg"),
    ],
    originalFilename: "Foto 22.jpeg",
    alt: "Fotografía en entorno urbano",
    category: "travel",
    caption: "Vivir el momento con el corazón lleno",
    subCaption: "Fotografía 22 · Metrópoli",
    orientation: "portrait",
  },
  {
    id: 23,
    src: publicAsset("/media/photos/foto-23.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/Foto 23.jpeg"),
      publicAsset("/media/photos/photo-23.jpg"),
    ],
    originalFilename: "Foto 23.jpeg",
    alt: "Escenario nevado de ensueño",
    category: "travel",
    caption: "El mundo contigo es aún más lindo",
    subCaption: "Fotografía 23 · Invierno",
    orientation: "landscape",
  },

  // 4. Fotografías Compartidas y Cierre (Fotos 10, 25, 26, 27, 28)
  {
    id: 10,
    src: publicAsset("/media/photos/foto-10.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/foto 10.jpeg"),
      publicAsset("/media/photos/Foto 10.jpeg"),
      publicAsset("/media/photos/photo-10.jpg"),
    ],
    originalFilename: "foto 10.jpeg",
    alt: "Risas compartidas",
    category: "closing",
    caption: "Complicidad en cada mirada",
    subCaption: "Fotografía 10 · Nosotros",
    orientation: "portrait",
  },
  {
    id: 25,
    src: publicAsset("/media/photos/foto-25.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/foto 25.jpeg"),
      publicAsset("/media/photos/Foto 25.jpeg"),
      publicAsset("/media/photos/photo-25.jpg"),
    ],
    originalFilename: "foto 25.jpeg",
    alt: "Momentos inolvidables juntos",
    category: "closing",
    caption: "De esos instantes que se quedan para siempre",
    subCaption: "Fotografía 25 · Momentos",
    orientation: "landscape",
  },
  {
    id: 26,
    src: publicAsset("/media/photos/foto-26.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/foto 26.jpeg"),
      publicAsset("/media/photos/Foto 26.jpeg"),
      publicAsset("/media/photos/photo-26.jpg"),
    ],
    originalFilename: "foto 26.jpeg",
    alt: "Abrazos y risas",
    category: "closing",
    caption: "Tu felicidad es mi lugar favorito",
    subCaption: "Fotografía 26 · Amor",
    orientation: "portrait",
  },
  {
    id: 27,
    src: publicAsset("/media/photos/foto-27.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/foto 27.jpeg"),
      publicAsset("/media/photos/Foto 27.jpeg"),
      publicAsset("/media/photos/photo-27.jpg"),
    ],
    originalFilename: "foto 27.jpeg",
    alt: "Celebrando el camino juntos",
    category: "closing",
    caption: "Por todo lo que todavía nos queda por vivir",
    subCaption: "Fotografía 27 · Futuro",
    orientation: "landscape",
  },
  {
    id: 28,
    src: publicAsset("/media/photos/foto-28.webp"),
    fallbackSrcs: [
      publicAsset("/media/photos/Foto 28.jpeg"),
      publicAsset("/media/photos/photo-28.jpg"),
    ],
    originalFilename: "Foto 28.jpeg",
    alt: "Feliz cumpleaños, mi amor",
    category: "closing",
    caption: "Te amo, Vale. Hoy, mañana y siempre.",
    subCaption: "Fotografía 28 · Cierre",
    focalPoint: "center",
    orientation: "portrait",
  },
];
